### ISSUE TITLE
Invalid argument

### ISSUE THREAD

**Issue by mistrysiddh** [pinheadmz/mobilebcoin#1]
```Invalid argument: --standalone.```
when i use this code ```bpkg --browser --standalone --plugin [ uglify-es --toplevel ] --name BCOIN --output <path to this repo>/bcoin.js lib/bcoin.js```

**Comment by pinheadmz** [comment]
This project is a bit out of date, please see the actual documentation for `bpkg`: https://github.com/chjj/bpkg
